services:
  mysql:
    image: mysql:latest
    container_name: paste-and-forget-mysql
    restart: always
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: paste_and_forget
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  mongo:
    image: mongo:latest
    container_name: paste-and-forget-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
