spring:
  data:
    mongodb:
      username: yakuza
      password: greatpassword
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/test
    username: yakuza
    password: greatpassword
    pool:
      validation-query: SELECT 1
server:
  port: 8089
