spring:
  data:
    mongodb:
      username: user
      password: pass
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/paste_and_forget
    username: user
    password: pass
    pool:
      validation-query: SELECT 1
    properties:
      ssl: false
server:
  port: 8089
